

const ReadMore = () => {
    return (
        <div className="hero-overlay bg-opacity-60 text-neutral-content p-20 text-lg">
            <p>
                1. <u><b> Army Administered & UGC Approved:</b></u> Bangladesh Army International University of Science and Technology (BAIUST) runs under the direct supervision of the Bangladesh Army. Its programs are approved by UGC. The Vice-Chancellor (VC) is selected from the teachers of the Military Institute of Science & Technology (MIST) and approved by the Chancellor— the Honorable President of Bangladesh.
                <br /> 2. <u><b> Access to the VC:</b></u> The University gives top priority to its students and provides utmost care to students’ needs. All the students have access to the VC for their educational, administrative, and personal requirements when necessary. In addition, the VC interacts with all students regularly. The VC and faculties also interact with parents/guardians when required.
                <br /> 3. <u><b> Permanent Campus:</b></u> Presently, BAIUST conducts its present academic programs from it’s permanent campus having 10.18 acres of land in Sayedpur, Adarsha Sadar, Cumilla. The facilities of the BAIUST permanent  campus include separate academic and administrative buildings, auditorium, halls for male and female students, digital library, well-equipped laboratories, playground, central dining hall, cafeteria, mosque, etc. The University started its function in permanent campus from January 2023.
                <br /> 4. <u><b>Outcome-based Education (OBE):</b></u> BAIUST has introduced its OBE curriculum since Spring 2022. In the OBE system, employers’ requirements directly become the program  syllabus. Thus, OBE will enhance the employability of BAIUST graduates, nationally and internationally.
                <br /> 5. <u><b>Qualified Academics:</b></u> Our faculty members are highly qualified with brilliant academic backgrounds. Many have vast experience in teaching and research. Quality education  facilitated by qualified teachers is our promise.
                <br /> 6. <u><b>Club Activities:</b></u> The University has a lot of co-curricular activities for students under 11 clubs, such as sports club, cultural club, debate club, photography club, language club etc. BAIUST encourages students to be involved in co-curricular activities to attain knowledge, managerial skills, leadership skills, and real-life experiences by which they can meet the current world needs.
                <br /> 7. <u><b>Disciplined and Secured Environment:</b></u> BAIUST ensures a secured and disciplined educational environment. It is free from politics, drugs, eve-teasing, raging, and subversive activities. Any breach of discipline is promptly dealt with.
                <br /> 8. <u><b>Mentoring and Special Counseling:</b></u> Each student is assigned to a mentor (teacher), who acts as a local guardian of the student. If any student’s academic performance is not satisfactory, mentors and other faculty members provide them with counseling to improve their performance.
                <br /> 9. <u><b>Certificate Courses:</b></u> BAIUST offers different short-term certificate courses helpful for students’ careers immediately after graduation. This increases the probability of getting employed.
                <br /> 10. <u><b>Green Campus:</b></u> The campus is in a calm, serene, green, and pollution-free open environment that helps students touch nature every day.
                <br /> 11. <u><b>Waiver and Scholarship:</b></u> Every semester, students avail waivers and scholarships on tuition fees in various categories, such as children of freedom fighters 100%, poor but meritorious waiver up to 100%, merit-based waiver up to 40%, sibling waiver 25%, children/spouse of military personnel 10%, etc.
                <br /> 12. <u><b>Transport Facility:</b></u> The University has its own transportation facilities for non-resident students.
                <br /> 13. <u><b>Culture of Timeliness:</b></u> BAIUST is committed to ensuring an uninterrupted curriculum so that students can complete their degrees and be in the job market without any delay.
                <br /> 14. <u><b>Developing Good Citizen:</b></u> BAIUST, through its curricular and co-curricular activities, focuses on developing students as good human beings with all possible positive attributes.
                <br /> 15. <u><b>Our Alumni:</b></u> BAIUST produces competent graduates in their designated fields. Up to Fall 2022, a total of 1121 students have graduated. Among them, 334 graduates have already got jobs in different reputed organizations, and 206 have enrolled for higher studies at different reputed public and private universities at home and abroad. Alumni Association also helps fresh graduates in the job market. Gradually, their valued and continual feedback will help update the curriculum to meet the present day needs of the society.</p>
        </div>
    );
};

export default ReadMore;